services:
  - type: web
    name: yt-notes-backend
    env: docker
    dockerContext: backend
    dockerfilePath: backend/Dockerfile
    plan: free
    region: ohio
    envs:
      - key: PORT
        value: 8000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: APP_SECRET_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
    healthCheckPath: /api/v1/health
    numInstances: 1
